"""Add homepage CMS tables

Revision ID: 7f6f1d60b417
Revises: e039e7f140fc
Create Date: 2026-09-09 15:55:29.434053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6f1d60b417'
down_revision = 'e039e7f140fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('homepage_content', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(batch_op.f('uq_homepage_content_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_homepage_content_key'))
        batch_op.create_index(batch_op.f('ix_homepage_content_key'), ['key'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.create_unique_constraint('uq_orders_order_code', ['order_code'])

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_wishlist_user_product', ['user_id', 'product_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('uq_wishlist_user_product', type_='unique')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('order_code',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('homepage_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homepage_content_key'))
        batch_op.create_index(batch_op.f('ix_homepage_content_key'), ['key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_homepage_content_key'), ['key'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
